# -*- coding: utf-8 -*-
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 moieboy9999 - Micro Dog
"""
Generate urdf/micro_dog.urdf from params/robot_params.yaml.

Link / joint names follow the Unitree Go2 convention so that the Isaac Lab
Go2 task configuration can be reused with minimal edits:

    base
    {FL,FR,RL,RR}_hip    <- {FL,..}_hip_joint    (roll,  axis +X)
    {FL,FR,RL,RR}_thigh  <- {FL,..}_thigh_joint  (pitch, axis +Y)
    {FL,FR,RL,RR}_calf   <- {FL,..}_calf_joint   (knee,  axis +Y)
    {FL,FR,RL,RR}_foot   <- {FL,..}_foot_joint   (fixed)

Run:  python generate_urdf.py [--mesh-prefix ../meshes/visual] [--no-visual-mesh]
"""
import argparse
import io
import os
import xml.dom.minidom as minidom

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

LEGS = ('FL', 'FR', 'RL', 'RR')
JOINT_KIND = {'hip': 'hip', 'thigh': 'thigh', 'calf': 'calf'}

MATERIALS = """  <material name="body_grey">   <color rgba="0.35 0.36 0.38 1.0"/></material>
  <material name="link_white">  <color rgba="0.85 0.86 0.88 1.0"/></material>
  <material name="joint_orange"><color rgba="0.90 0.45 0.10 1.0"/></material>
  <material name="foot_black">  <color rgba="0.08 0.08 0.08 1.0"/></material>
"""

MAT_OF = {'base': 'body_grey', 'hip': 'joint_orange', 'thigh': 'link_white',
          'calf': 'link_white', 'foot': 'foot_black'}


def f(x):
    return ('%.8g' % float(x))


def vec(v):
    return ' '.join(f(x) for x in v)


def inertial(link):
    I = link['inertia']
    return (
        '    <inertial>\n'
        '      <origin xyz="%s" rpy="0 0 0"/>\n'
        '      <mass value="%s"/>\n'
        '      <inertia ixx="%s" ixy="%s" ixz="%s" iyy="%s" iyz="%s" izz="%s"/>\n'
        '    </inertial>\n' % (
            vec(link['com']), f(link['mass']),
            f(I['ixx']), f(I['ixy']), f(I['ixz']),
            f(I['iyy']), f(I['iyz']), f(I['izz'])))


def collision(link):
    c = link.get('collision')
    if not c:
        return ''
    if c['type'] == 'box':
        geom = '<box size="%s"/>' % vec(c['size'])
    elif c['type'] == 'sphere':
        geom = '<sphere radius="%s"/>' % f(c['radius'])
    else:
        raise ValueError(c['type'])
    return ('    <collision>\n'
            '      <origin xyz="%s" rpy="0 0 0"/>\n'
            '      <geometry>%s</geometry>\n'
            '    </collision>\n' % (vec(c['origin']), geom))


def visual(link, name, prefix, use_mesh):
    mat = MAT_OF[name.split('_')[-1] if '_' in name else name]
    mesh = link.get('mesh')
    if use_mesh and mesh:
        geom = '<mesh filename="%s/%s.stl" scale="1 1 1"/>' % (prefix.rstrip('/'), mesh)
        origin = '0 0 0'
    else:
        c = link.get('collision')
        if not c:
            return ''
        if c['type'] == 'box':
            geom = '<box size="%s"/>' % vec(c['size'])
        else:
            geom = '<sphere radius="%s"/>' % f(c['radius'])
        origin = vec(c['origin'])
    return ('    <visual>\n'
            '      <origin xyz="%s" rpy="0 0 0"/>\n'
            '      <geometry>%s</geometry>\n'
            '      <material name="%s"/>\n'
            '    </visual>\n' % (origin, geom, mat))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--mesh-prefix', default='../meshes/visual')
    ap.add_argument('--no-visual-mesh', action='store_true',
                    help='use collision primitives as visuals (tiny file, fast to load)')
    ap.add_argument('--out', default=os.path.join(ROOT, 'urdf', 'micro_dog.urdf'))
    args = ap.parse_args()

    with io.open(os.path.join(ROOT, 'params', 'robot_params.yaml'), encoding='utf-8') as fh:
        P = yaml.safe_load(fh)

    act = P['actuator']
    lim = P['limits']
    links, joints = P['links'], P['joints']

    body = []
    body.append('<?xml version="1.0"?>\n')
    body.append('<!-- %s\n' % P['meta']['name'])
    for k in ('description', 'source_cad', 'frame', 'zero_pose', 'knee_linkage'):
        body.append('     %-14s %s\n' % (k + ':', P['meta'][k]))
    body.append('     generated by tools/generate_urdf.py - edit upstream sources, not this file\n')
    body.append('-->\n')
    body.append('<robot name="%s">\n\n' % P['meta']['name'])
    body.append(MATERIALS)
    body.append('\n')

    order = ['base']
    for leg in LEGS:
        order += ['%s_%s' % (leg, s) for s in ('hip', 'thigh', 'calf', 'foot')]

    for name in order:
        L = links[name]
        body.append('  <link name="%s">\n' % name)
        body.append(inertial(L))
        body.append(visual(L, name, args.mesh_prefix, not args.no_visual_mesh))
        body.append(collision(L))
        body.append('  </link>\n\n')

    for leg in LEGS:
        for kind in ('hip', 'thigh', 'calf'):
            jn = '%s_%s_joint' % (leg, kind)
            J = joints[jn]
            joint_limits = lim[kind]
            side = 'left' if leg.endswith('L') else 'right'
            joint_limits = joint_limits.get(side, joint_limits)
            lo, hi = joint_limits['lower'], joint_limits['upper']
            body.append(
                '  <joint name="%s" type="revolute">\n'
                '    <parent link="%s"/>\n'
                '    <child link="%s"/>\n'
                '    <origin xyz="%s" rpy="0 0 0"/>\n'
                '    <axis xyz="%s"/>\n'
                '    <limit lower="%s" upper="%s" effort="%s" velocity="%s"/>\n'
                '    <dynamics damping="%s" friction="%s"/>\n'
                '  </joint>\n\n' % (
                    jn, J['parent'], J['child'], vec(J['origin']), vec(J['axis']),
                    f(lo), f(hi), f(act['effort_limit']), f(act['velocity_limit']),
                    # URDF <dynamics> is the joint's *mechanical* loss, so this is
                    # BAM's viscous/Coulomb friction -- NOT the actuator damping,
                    # which is the motor's back-EMF and belongs to the PD model.
                    f(act['viscous_friction']), f(act['friction'])))
        jn = '%s_foot_joint' % leg
        J = joints[jn]
        body.append(
            '  <joint name="%s" type="fixed">\n'
            '    <parent link="%s"/>\n'
            '    <child link="%s"/>\n'
            '    <origin xyz="%s" rpy="0 0 0"/>\n'
            '  </joint>\n\n' % (jn, J['parent'], J['child'], vec(J['origin'])))

    body.append('</robot>\n')
    text = ''.join(body)

    # sanity: must parse
    minidom.parseString(text.split('-->', 1)[-1] if False else text)

    outdir = os.path.dirname(args.out)
    if outdir and not os.path.isdir(outdir):
        os.makedirs(outdir)
    with io.open(args.out, 'w', encoding='utf-8') as fh:
        fh.write(text)
    print('wrote %s  (%d links, %d joints)' % (args.out, len(order), len(joints)))


if __name__ == '__main__':
    main()
